XGBOOST_PARAMS:
  n_estimators: [50, 100, 200]
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 5, 7]
  random_state: 6


KF_PARAMS:
  n_splits: 3
  shuffle: True
  random_state: 6


CV_PARAMS:
  scoring: neg_mean_squared_error
  n_jobs: -1
  verbose: 1
  
