artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://archive.ics.uci.edu/static/public/186/wine+quality.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  data_file_csv: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_file_csv: artifacts/data_ingestion/winequality-red.csv


model_training: 
  root_dir: artifacts/model_training
  train_df_path: artifacts/data_transformation/train.csv
  test_df_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  best_params_path: artifacts/model_training/best_params.json


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_X_path: artifacts/model_training/X_test.csv
  test_y_path: artifacts/model_training/y_test.csv
  model_path: artifacts/model_training/model.joblib
  model_metrics: artifacts/model_evaluation/model_metrics.json
  best_params_path: artifacts/model_training/best_params.json